title: Cosmic Python - Simple Patterns for Building Complex Applications
theme: jekyll-theme-minimal
permalink: /blog/:year-:month-:day-:title.html
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
