title: Cosmic Python - Simple Patterns for Building Complex Applications
remote_theme: daviddarnes/alembic
permalink: /blog/:year-:month-:day-:title.html
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-remote-theme
